import { Inter } from "next/font/google";
import Header from "./components/header/header";
import "bootstrap/dist/css/bootstrap.css";
import BootstrapClient from "./components/BootStrapClient";
import "./globals.css";
import Footer from "./components/footer/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div className="page-content">
          {children}
        </div>
        <Footer />
        <BootstrapClient />
      </body>
    </html>
  );
}
